deployment:
  replicaCount: 2
  name: excelexplore-deployment
  image:
    repository: mizanussayed/excelexplore
    tag: latest

database:
  name: postgres
  secretName: postgres-secret
  username: appuser
  dbname: appdb
  password: STRONGPASSWORD  # Override this in secrets.yaml or with --set flag
