deployment:
  replicaCount: 2
  name: dotnet-api
  image:
    repository: mizanussayed/dotnet-api
    tag: latest

database:
  name: postgres
  secretName: postgres-secret
  username: appuser
  dbname: appdb
  password: STRONGPASSWORD  # Override this in secrets.yaml or with --set flag
