apiVersion: v1
kind: Pod
metadata:
  name: limited-pod
spec:
  containers:
  - name: nginx-ctr
    image: polinux/stress
    resources:
        limits:
          memory: "500Mi"
          cpu: "500m"
        requests:
          memory: "20Mi"
    command: ["stress"]
    args: ["--vm", "1", "--vm-bytes", "64M", "--vm-hang", "1"]