apiVersion: v1
kind: Pod
metadata:
  name: normal-volume-example
spec:
   volumes:
   - name: test-volume
     emptyDir: {}
   containers: 
    - name: test-cont
      image: nginx
      volumeMounts:
      - name: test-volume
        mountPath: /var/www
---
apiVersion: v1
kind: PersistentVolume
metadata:
 name: task-pv-volume
 labels:
   type: local
spec:
   storageClassName: standard
   capacity:
     storage: 1Gi
   accessModes:
   - ReadWriteOnce
   hostPath:
      path: "/storage-k8s"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: task-pv-claim
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
---
apiVersion: v1
kind: Pod
metadata:
  name: pv-claim-pod
spec:
  volumes:
    - name: task-pv-storage
      persistentVolumeClaim:
        claimName: task-pv-claim
  containers:
    - name: task-pv-container
      image: nginx
      volumeMounts:
        - mountPath: "/usr/share/nginx/html"
          name: task-pv-storage