apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
spec:
  containers:
   - name: nginx-ctr
     image: nginx

  affinity:
    nodeAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 1
        preference:
          matchExpressions:
          - key: disktype
            operator: In
            values:
            - ssd