apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: dotnet-api
    releaseName: dotnet-api
    repo: file://../../helm
    version: 0.1.0
    valuesFile: values.yaml
