service:
  name: mongodb-service
  port: 27017
  targetPort: 27017


storageClass:
  name: mongodb-sc
  provisioner: kubernetes.io/no-provisioner
  volumeBindingMode: WaitForFirstConsumer
  reclaimPolicy: Retain

persistence:
  count: 3
  basePath: /mnt/data
  volumeName: mongodb-pv

stateful:
  name: mongodb
  replicas: 3
  image: mongo:4.4
  volumeName: mongodb-data
  volumeMountPath: /data/db