apiVersion: v1
kind: Pod
metadata:
  name: request-limit-pod
spec:
  containers:
    - name: request-limit-containers
      image: polinux/stress
      resources:
        requests:
          memory: "50Mi"
        limits:
          cpu: "1"
          memory: "70Mi"
      command: ["stress"]
      args: ["--cpu", "2", "--vm", "1", "--vm-bytes", "256M", "--timeout", "600s"]
---
apiVersion: v1
kind: Pod
metadata:
  name: no-request-limit-pod
spec:
  containers:
    - name: no-request-limit-containers
      image: polinux/stress
      command: ["stress"]
      args: ["--cpu", "2", "--vm", "1", "--vm-bytes", "256M", "--timeout", "600s"]