apiVersion: v1
kind: ServiceAccount
metadata:
 name: sa-demo
 namespace: default
---
apiVersion: v1
kind: Pod
metadata:
 name: demo-pod-sa
spec:
 serviceAccountName: sa-demo
 containers: 
 - name: demo-ctr
   image: nginx
