apiVersion: v1
kind: Service
metadata:
  {{- with .Values.deployment }}
  name: {{ .name }}-service
spec:
  type: ClusterIP
  selector:
    app: {{ .name }}
  ports:
    - port: 80
      targetPort: 8080
{{- end }}
