apiVersion: apps/v1
kind: Deployment
{{- with .Values.deployment }}
metadata:
  name: {{ .name }}-deployment
spec:
  replicas: {{ .replicaCount }}
  selector:
    matchLabels:
      app: {{ .name }}
  template:
    metadata:
      labels:
        app: {{ .name }}
    spec:
      containers:
        - name: api
          image: "{{ .image.repository }}:{{ .image.tag }}"
          ports:
            - containerPort: 8080
          env:
            - name: ConnectionStrings__DefaultConnection
              valueFrom:
                secretKeyRef:
                  name: {{ $.Values.database.secretName }}
                  key: CONNECTION_STRING
{{- end }}
