apiVersion: v1
kind: Pod
metadata:
  name: affinity-example
spec:
  containers:
  - name: nginx
    image: nginx
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoreDuringExecution:
       nodeSelectorTerms:
       - key: disktype
         operator: Equal
         values:
         - ssd