{{- range $i := until (.Values.persistence.count | int) }}
apiVersion: v1
kind: PersistentVolume
metadata:
 name: {{ $.Values.persistence.volumeName }}-{{ $i }}
 labels:
    type: local
spec:
  storageClassName: {{ $.Values.storageClass.name }}
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: {{ $.Values.persistence.basePath }}/{{ $.Values.persistence.volumeName }}-{{ $i }}
  persistentVolumeReclaimPolicy: {{ $.Values.storageClass.reclaimPolicy }}
---
{{- end }}