resources: 
- deployment.yaml
- service.yaml

commonLabels:
  app: myapp

commonAnnotations:
  owner: mizanussayed

namePrefix: 
  kustom-
nameSuffix:
  -v1

configMapGenerator:
- name: myapp-config
  env: config.properties