apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment
spec:
  replicas: 3
  selector:
  template:
    metadata:
    spec: 
      containers:
      - name: myapp-container
        image: nginx:latest
        ports:
        - containerPort: 80