apiVersion: batch/v1
kind: CronJob
metadata:
 name: my-cronjob
spec:
 schedule: "*/5 * * * *"
 jobTemplate:
  spec:
   template:
    spec:
     containers:
      - name: test-container
        image: nginx
        args: 
        -  /bin/sh
        - -c
        - date; echo Hello from the kubernetes CronJob!
     restartPolicy: OnFailure
